all:
	g++ -std=c++11 ahmet_hilmi_berber_171044027.cpp employee.cpp university.cpp academicpersonnel.cpp administrativepersonnel.cpp lecturer.cpp officer.cpp researchassistant.cpp secretary.cpp -o out
	./out

clean:
	rm out